mongo_uri = ""
elastic_uri = ""
database = "sample_mflix"
app_name = "example-rs"
collection = "comments"
port = 8080
search_index = "kibana_sample_data_ecommerce"
auth_header_name = "X-Blyad-Value"
auth_header_value = "hehe"
[kafka]
servers = ""
username = ""
password = ""
group_id = "maia-test"
topic = "2jr5id3d-default"